package solutions.No_0389_find_the_difference;

/**
 * https://leetcode.com/problems/find-the-difference/
 * @author Nacht
 * Created on 2019/5/27
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 * Example:
 * Input:
 * s = "abcd"
 * t = "abcde"
 * Output:
 * e
 * Explanation:
 * 'e' is the letter that was added.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * 解题思路:
 * 将t中所有字符的ascii值之和减去s中所有字符的ascii值之和即可
 */
public class Solution {
    public char findTheDifference(String s, String t) {
        char c = 0;
        for(int i = 0 ; i < s.length() ; i++){
            c += t.charAt(i) - s.charAt(i);
        }
        c += t.charAt(t.length()-1);
        return c;
    }

    public static void main(String[] args) {
        System.out.println(new Solution().findTheDifference("abcc","abccf"));
    }
}